### ISSUE TITLE
Responsividade Hero e Reviews

### ISSUE THREAD

**Issue by pecraveiro** [ogruposix/vitasix-ecommerce#7]
- [ ] Tornar o componente Hero responsivo para mobile
- [ ] Tornar o componente Reviews responsivo para mobile

**Comment by trichains** [comment]
Hero: https://github.com/ogruposix/vitasix-ecommerce/commit/78b49a8e8ad231f6c0ab13339838195795cbdf53

Review: https://github.com/ogruposix/vitasix-ecommerce/commit/6df185d0f2dc48b4a27119833c0e6ff631de1ac3
